trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
#      Python37Windows:
#        imageName: 'windows-latest'
#        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
# 3.11 Prodigy wheels not available yet
#      Python311Linux:
#        imageName: 'ubuntu-latest'
#        python.version: '3.11'
#      Python311Windows:
#        imageName: 'windows-latest'
#        python.version: '3.11'
#      Python311Mac:
#        imageName: 'macos-latest'
#        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install -U build pip setuptools
      python -m pip install prodigy -f https://$(PRODIGY_KEY)@download.prodi.gy
      pip install -U -r requirements.txt
    displayName: 'Install dependencies'
    env:
      PRODIGY_KEY: $(PRODIGY_KEY)

  - script: python -m pytest
    displayName: 'Run tests'
