trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
# 3.11 Prodigy wheels not available yet
#      Python311Linux:
#        imageName: 'ubuntu-latest'
#        python.version: '3.11'
#      Python311Windows:
#        imageName: 'windows-latest'
#        python.version: '3.11'
#      Python311Mac:
#        imageName: 'macos-latest'
#        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - name: Check out Prodigy
    uses: actions/checkout@v3
    with:
      repository: explosion/prodigy
      ref: v1.11.8
      path: ./prodigy
      ssh-key: ${{ secrets.GHA_PRODIGY_READ }}

  - name: Install prodigy
    run: |
      ls -la
      pip install ./prodigy

  - script: |
      python -m pip install -U build pip setuptools
      pip install -U -r requirements.txt
    displayName: 'Install dependencies'

  - script: python -m pytest
    displayName: 'Run tests'
